#!/bin/bash
curdir=$(pwd)
#
cd ~/st-device-sdk-c
if [ -f "src/port/bsp/posix/iot_bsp_wifi_posix.c" ]; then
  mv src/port/bsp/posix/iot_bsp_wifi_posix.c src/port/bsp/posix/iot_bsp_wifi_posix.ORIGc
fi
#
cp ~/rpi-st-device/iot_bsp_wifi_rpi.c src/port/bsp/posix/iot_bsp_wifi_rpi.c
#
# remove any existing wifi object build modules to avoid user errors
rm -f build/stdk_iot_bsp_wifi_posix.o
#
###########################################################################
### core SDK patches - remove when released ###
# (1) timer memory leak & (2) eventgroup mutex
#cp ~/rpi-st-device/iot_os_util_posix.c src/port/os/posix/iot_os_util_posix.c
# (3) MBEDTLS link module list update
#cp ~/rpi-st-device/mbedtls_Makefile src/deps/mbedtls/Makefile
############################################################################
#
# Set-clock bypass
if [ -f "src/port/bsp/posix/iot_bsp_system_posix.c" ]; then
  mv src/port/bsp/posix/iot_bsp_system_posix.c src/port/bsp/posix/iot_bsp_system_posix.ORIGc
fi
cp ~/rpi-st-device/iot_bsp_system_rpi.c src/port/bsp/posix/iot_bsp_system_rpi.c
rm -f build/stdk_iot_bsp_system_posix.o
#
if [ ! -f "stdconfigORIG" ]; then mv stdkconfig stdkconfigORIG; fi
cp ~/rpi-st-device/RPIstdkconfig stdkconfig
#
cp ~/rpi-st-device/softapstart ~/st-device-sdk-c/example/softapstart
cp ~/rpi-st-device/softapstop ~/st-device-sdk-c/example/softapstop
#
cp ~/rpi-st-device/sdkbuildsetup ~/st-device-sdk-c/sdkbuildsetup
